### ISSUE TITLE
trickyfetch breaks repoman

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/trickyfetch#2]
1) delete `/var/lib/portage/distfiles/metadata.xsd`
2) run `repoman full -d -x`
```

RepoMan scours the neighborhood...

*** the local copy of metadata.xsd needs to be refetched, doing that now

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/repoman", line 45, in <module>
    sys.exit(repoman_main(sys.argv[1:]))
  File "/usr/lib/python3.7/site-packages/repoman/main.py", line 122, in repoman_main
    scanner.scan_pkgs(can_force)
  File "/usr/lib/python3.7/site-packages/repoman/scanner.py", line 334, in scan_pkgs
    _continue = func(**self.set_func_kwargs(mod, dynamic_data))
  File "/usr/lib/python3.7/site-packages/repoman/modules/scan/metadata/pkgmetadata.py", line 159, in check
    validator = etree.XMLSchema(file=self.metadata_xsd)
  File "src/lxml/xmlschema.pxi", line 86, in lxml.etree.XMLSchema.__init__
lxml.etree.XMLSchemaParseError: Failed to parse the XML resource '/var/lib/portage/distfiles/metadata.xsd'.
```

now `/var/lib/portage/distfiles/metadata.xsd` is empty

If I remove `FETCHCOMMAND` from `make.conf` then repoman will work
```

RepoMan scours the neighborhood...

*** the local copy of metadata.xsd needs to be refetched, doing that now

--2019-09-11 11:01:09--  https://www.gentoo.org/xml-schema/metadata.xsd
Risoluzione di www.gentoo.org (www.gentoo.org)... 89.16.167.134, 2001:41c8:0:936::136, 2001:41c8:0:936::139
Connessione a www.gentoo.org (www.gentoo.org)|89.16.167.134|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 18186 (18K) [application/octet-stream]
Salvataggio in: "/var/lib/portage/distfiles/metadata.xsd.dp6ad7_k"

/var/lib/portage/distfiles/metadata.xsd.dp6ad7_k            100%[========================================================================================================================================>]  17,76K  --.-KB/s    in 0,002s

2019-09-11 11:01:10 (6,99 MB/s) - "/var/lib/portage/distfiles/metadata.xsd.dp6ad7_k" salvato [18186/18186]

```

**Comment by vaeth** [comment]
I would rather say that repoman is broken:
repoman generates a random file of size 0 and expects FETCHCOMMAND to override it.
While this would be correct behaviour in a world-writable directory, this is complete nonsense in $PORTDIR.

The only workaround I could imagine is that trickyfetch considers files of 0 size as nonexistent and always downloads them. This, however, is against the purpose of trickyfetch if there actually *is* a file of size 0: This would always be downloaded anew.
